title: Repositório de Bordo
email: leonardogomes@ime.usp.br
description: >- # this means to ignore newlines until "baseurl:"
  Para aqueles (ou eu) que estão lendo... aqui não é estático, é fluxo de avanço e regresso.
baseurl: /repositorio-de-bordo
url: https://leosilvagomes.github.io
github_username: LeoSilvaGomes
instagram_username: ""
collections:
  sections:
    output: true
  profissional-experience:
    output: true
  about:
    output: true
  habilities:
    output: true
  qualification:
    output: true
  project-experience:
    output: true
  volunteer-experience:
    output: true
  habilities:
    output: false
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
