name: Test Workflow

on:
  issues:
    types: [edited, labeled]

jobs:
  edit-file:
    if: github.event.label || github.event.changes
    runs-on: ubuntu-latest

    steps:
      - name: Test modular workflow
        uses: LeoSilvaGomes/jekyll-actions/blob/main/.github/workflows/actions.yaml@main
        with:
          post-tag: "test-post"
