name: Test Workflow

on:
  issues:
    types: [edited, labeled]

jobs:
  test-file:
    if: github.event.label || github.event.changes
    uses: LeoSilvaGomes/jekyll-actions/.github/workflows/action.yaml@main
    with:
      post-tag: "test-post"
